//! Custom statistics identifiers.
//!
//! Each variant maps to one entry in vanilla's `CUSTOM_STAT` registry.
//! The discriminant value is the registry index used on the wire (`C_AWARD_STATS`).
//! The order **must** match `Stats.java` field declaration order.

use steel_utils::Identifier;

/// All vanilla custom statistics, ordered to match the `CUSTOM_STAT` registry.
///
/// Differs from vanilla naming in that we use Rust naming conventions while keeping
/// the 1:1 mapping. The `identifier()` method returns the canonical `minecraft:` key.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u32)]
#[expect(missing_docs, reason = "self-documenting registry entries; names mirror vanilla identifiers")]
pub enum CustomStat {
    LeaveGame = 0,
    PlayTime = 1,
    TotalWorldTime = 2,
    TimeSinceDeath = 3,
    TimeSinceRest = 4,
    SneakTime = 5,
    WalkOneCm = 6,
    CrouchOneCm = 7,
    SprintOneCm = 8,
    WalkOnWaterOneCm = 9,
    FallOneCm = 10,
    ClimbOneCm = 11,
    FlyOneCm = 12,
    WalkUnderWaterOneCm = 13,
    MinecartOneCm = 14,
    BoatOneCm = 15,
    PigOneCm = 16,
    HappyGhastOneCm = 17,
    HorseOneCm = 18,
    AviateOneCm = 19,
    SwimOneCm = 20,
    StriderOneCm = 21,
    NautilusOneCm = 22,
    Jump = 23,
    Drop = 24,
    DamageDealt = 25,
    DamageDealtAbsorbed = 26,
    DamageDealtResisted = 27,
    DamageTaken = 28,
    DamageBlockedByShield = 29,
    DamageAbsorbed = 30,
    DamageResisted = 31,
    Deaths = 32,
    MobKills = 33,
    AnimalsBred = 34,
    PlayerKills = 35,
    FishCaught = 36,
    TalkedToVillager = 37,
    TradedWithVillager = 38,
    EatCakeSlice = 39,
    FillCauldron = 40,
    UseCauldron = 41,
    CleanArmor = 42,
    CleanBanner = 43,
    CleanShulkerBox = 44,
    InteractWithBrewingstand = 45,
    InteractWithBeacon = 46,
    InspectDropper = 47,
    InspectHopper = 48,
    InspectDispenser = 49,
    PlayNoteblock = 50,
    TuneNoteblock = 51,
    PotFlower = 52,
    TriggerTrappedChest = 53,
    OpenEnderchest = 54,
    EnchantItem = 55,
    PlayRecord = 56,
    InteractWithFurnace = 57,
    InteractWithCraftingTable = 58,
    OpenChest = 59,
    SleepInBed = 60,
    OpenShulkerBox = 61,
    OpenBarrel = 62,
    InteractWithBlastFurnace = 63,
    InteractWithSmoker = 64,
    InteractWithLectern = 65,
    InteractWithCampfire = 66,
    InteractWithCartographyTable = 67,
    InteractWithLoom = 68,
    InteractWithStonecutter = 69,
    BellRing = 70,
    RaidTrigger = 71,
    RaidWin = 72,
    InteractWithAnvil = 73,
    InteractWithGrindstone = 74,
    TargetHit = 75,
    InteractWithSmithingTable = 76,
}

impl CustomStat {
    /// Total number of custom stats.
    pub const COUNT: usize = 77;

    /// Returns the vanilla `minecraft:` identifier for this stat.
    pub fn identifier(self) -> Identifier {
        let name = match self {
            Self::LeaveGame => "leave_game",
            Self::PlayTime => "play_time",
            Self::TotalWorldTime => "total_world_time",
            Self::TimeSinceDeath => "time_since_death",
            Self::TimeSinceRest => "time_since_rest",
            Self::SneakTime => "sneak_time",
            Self::WalkOneCm => "walk_one_cm",
            Self::CrouchOneCm => "crouch_one_cm",
            Self::SprintOneCm => "sprint_one_cm",
            Self::WalkOnWaterOneCm => "walk_on_water_one_cm",
            Self::FallOneCm => "fall_one_cm",
            Self::ClimbOneCm => "climb_one_cm",
            Self::FlyOneCm => "fly_one_cm",
            Self::WalkUnderWaterOneCm => "walk_under_water_one_cm",
            Self::MinecartOneCm => "minecart_one_cm",
            Self::BoatOneCm => "boat_one_cm",
            Self::PigOneCm => "pig_one_cm",
            Self::HappyGhastOneCm => "happy_ghast_one_cm",
            Self::HorseOneCm => "horse_one_cm",
            Self::AviateOneCm => "aviate_one_cm",
            Self::SwimOneCm => "swim_one_cm",
            Self::StriderOneCm => "strider_one_cm",
            Self::NautilusOneCm => "nautilus_one_cm",
            Self::Jump => "jump",
            Self::Drop => "drop",
            Self::DamageDealt => "damage_dealt",
            Self::DamageDealtAbsorbed => "damage_dealt_absorbed",
            Self::DamageDealtResisted => "damage_dealt_resisted",
            Self::DamageTaken => "damage_taken",
            Self::DamageBlockedByShield => "damage_blocked_by_shield",
            Self::DamageAbsorbed => "damage_absorbed",
            Self::DamageResisted => "damage_resisted",
            Self::Deaths => "deaths",
            Self::MobKills => "mob_kills",
            Self::AnimalsBred => "animals_bred",
            Self::PlayerKills => "player_kills",
            Self::FishCaught => "fish_caught",
            Self::TalkedToVillager => "talked_to_villager",
            Self::TradedWithVillager => "traded_with_villager",
            Self::EatCakeSlice => "eat_cake_slice",
            Self::FillCauldron => "fill_cauldron",
            Self::UseCauldron => "use_cauldron",
            Self::CleanArmor => "clean_armor",
            Self::CleanBanner => "clean_banner",
            Self::CleanShulkerBox => "clean_shulker_box",
            Self::InteractWithBrewingstand => "interact_with_brewingstand",
            Self::InteractWithBeacon => "interact_with_beacon",
            Self::InspectDropper => "inspect_dropper",
            Self::InspectHopper => "inspect_hopper",
            Self::InspectDispenser => "inspect_dispenser",
            Self::PlayNoteblock => "play_noteblock",
            Self::TuneNoteblock => "tune_noteblock",
            Self::PotFlower => "pot_flower",
            Self::TriggerTrappedChest => "trigger_trapped_chest",
            Self::OpenEnderchest => "open_enderchest",
            Self::EnchantItem => "enchant_item",
            Self::PlayRecord => "play_record",
            Self::InteractWithFurnace => "interact_with_furnace",
            Self::InteractWithCraftingTable => "interact_with_crafting_table",
            Self::OpenChest => "open_chest",
            Self::SleepInBed => "sleep_in_bed",
            Self::OpenShulkerBox => "open_shulker_box",
            Self::OpenBarrel => "open_barrel",
            Self::InteractWithBlastFurnace => "interact_with_blast_furnace",
            Self::InteractWithSmoker => "interact_with_smoker",
            Self::InteractWithLectern => "interact_with_lectern",
            Self::InteractWithCampfire => "interact_with_campfire",
            Self::InteractWithCartographyTable => "interact_with_cartography_table",
            Self::InteractWithLoom => "interact_with_loom",
            Self::InteractWithStonecutter => "interact_with_stonecutter",
            Self::BellRing => "bell_ring",
            Self::RaidTrigger => "raid_trigger",
            Self::RaidWin => "raid_win",
            Self::InteractWithAnvil => "interact_with_anvil",
            Self::InteractWithGrindstone => "interact_with_grindstone",
            Self::TargetHit => "target_hit",
            Self::InteractWithSmithingTable => "interact_with_smithing_table",
        };
        Identifier::vanilla_static(name)
    }

    /// All custom stat variants in registry order (index == discriminant).
    pub const ALL: [Self; Self::COUNT] = [
        Self::LeaveGame,
        Self::PlayTime,
        Self::TotalWorldTime,
        Self::TimeSinceDeath,
        Self::TimeSinceRest,
        Self::SneakTime,
        Self::WalkOneCm,
        Self::CrouchOneCm,
        Self::SprintOneCm,
        Self::WalkOnWaterOneCm,
        Self::FallOneCm,
        Self::ClimbOneCm,
        Self::FlyOneCm,
        Self::WalkUnderWaterOneCm,
        Self::MinecartOneCm,
        Self::BoatOneCm,
        Self::PigOneCm,
        Self::HappyGhastOneCm,
        Self::HorseOneCm,
        Self::AviateOneCm,
        Self::SwimOneCm,
        Self::StriderOneCm,
        Self::NautilusOneCm,
        Self::Jump,
        Self::Drop,
        Self::DamageDealt,
        Self::DamageDealtAbsorbed,
        Self::DamageDealtResisted,
        Self::DamageTaken,
        Self::DamageBlockedByShield,
        Self::DamageAbsorbed,
        Self::DamageResisted,
        Self::Deaths,
        Self::MobKills,
        Self::AnimalsBred,
        Self::PlayerKills,
        Self::FishCaught,
        Self::TalkedToVillager,
        Self::TradedWithVillager,
        Self::EatCakeSlice,
        Self::FillCauldron,
        Self::UseCauldron,
        Self::CleanArmor,
        Self::CleanBanner,
        Self::CleanShulkerBox,
        Self::InteractWithBrewingstand,
        Self::InteractWithBeacon,
        Self::InspectDropper,
        Self::InspectHopper,
        Self::InspectDispenser,
        Self::PlayNoteblock,
        Self::TuneNoteblock,
        Self::PotFlower,
        Self::TriggerTrappedChest,
        Self::OpenEnderchest,
        Self::EnchantItem,
        Self::PlayRecord,
        Self::InteractWithFurnace,
        Self::InteractWithCraftingTable,
        Self::OpenChest,
        Self::SleepInBed,
        Self::OpenShulkerBox,
        Self::OpenBarrel,
        Self::InteractWithBlastFurnace,
        Self::InteractWithSmoker,
        Self::InteractWithLectern,
        Self::InteractWithCampfire,
        Self::InteractWithCartographyTable,
        Self::InteractWithLoom,
        Self::InteractWithStonecutter,
        Self::BellRing,
        Self::RaidTrigger,
        Self::RaidWin,
        Self::InteractWithAnvil,
        Self::InteractWithGrindstone,
        Self::TargetHit,
        Self::InteractWithSmithingTable,
    ];

    /// Attempts to construct a `CustomStat` from its `minecraft:` identifier string.
    pub fn from_identifier(id: &str) -> Option<Self> {
        let name = id.strip_prefix("minecraft:").unwrap_or(id);
        match name {
            "leave_game" => Some(Self::LeaveGame),
            "play_time" => Some(Self::PlayTime),
            "total_world_time" => Some(Self::TotalWorldTime),
            "time_since_death" => Some(Self::TimeSinceDeath),
            "time_since_rest" => Some(Self::TimeSinceRest),
            "sneak_time" => Some(Self::SneakTime),
            "walk_one_cm" => Some(Self::WalkOneCm),
            "crouch_one_cm" => Some(Self::CrouchOneCm),
            "sprint_one_cm" => Some(Self::SprintOneCm),
            "walk_on_water_one_cm" => Some(Self::WalkOnWaterOneCm),
            "fall_one_cm" => Some(Self::FallOneCm),
            "climb_one_cm" => Some(Self::ClimbOneCm),
            "fly_one_cm" => Some(Self::FlyOneCm),
            "walk_under_water_one_cm" => Some(Self::WalkUnderWaterOneCm),
            "minecart_one_cm" => Some(Self::MinecartOneCm),
            "boat_one_cm" => Some(Self::BoatOneCm),
            "pig_one_cm" => Some(Self::PigOneCm),
            "happy_ghast_one_cm" => Some(Self::HappyGhastOneCm),
            "horse_one_cm" => Some(Self::HorseOneCm),
            "aviate_one_cm" => Some(Self::AviateOneCm),
            "swim_one_cm" => Some(Self::SwimOneCm),
            "strider_one_cm" => Some(Self::StriderOneCm),
            "nautilus_one_cm" => Some(Self::NautilusOneCm),
            "jump" => Some(Self::Jump),
            "drop" => Some(Self::Drop),
            "damage_dealt" => Some(Self::DamageDealt),
            "damage_dealt_absorbed" => Some(Self::DamageDealtAbsorbed),
            "damage_dealt_resisted" => Some(Self::DamageDealtResisted),
            "damage_taken" => Some(Self::DamageTaken),
            "damage_blocked_by_shield" => Some(Self::DamageBlockedByShield),
            "damage_absorbed" => Some(Self::DamageAbsorbed),
            "damage_resisted" => Some(Self::DamageResisted),
            "deaths" => Some(Self::Deaths),
            "mob_kills" => Some(Self::MobKills),
            "animals_bred" => Some(Self::AnimalsBred),
            "player_kills" => Some(Self::PlayerKills),
            "fish_caught" => Some(Self::FishCaught),
            "talked_to_villager" => Some(Self::TalkedToVillager),
            "traded_with_villager" => Some(Self::TradedWithVillager),
            "eat_cake_slice" => Some(Self::EatCakeSlice),
            "fill_cauldron" => Some(Self::FillCauldron),
            "use_cauldron" => Some(Self::UseCauldron),
            "clean_armor" => Some(Self::CleanArmor),
            "clean_banner" => Some(Self::CleanBanner),
            "clean_shulker_box" => Some(Self::CleanShulkerBox),
            "interact_with_brewingstand" => Some(Self::InteractWithBrewingstand),
            "interact_with_beacon" => Some(Self::InteractWithBeacon),
            "inspect_dropper" => Some(Self::InspectDropper),
            "inspect_hopper" => Some(Self::InspectHopper),
            "inspect_dispenser" => Some(Self::InspectDispenser),
            "play_noteblock" => Some(Self::PlayNoteblock),
            "tune_noteblock" => Some(Self::TuneNoteblock),
            "pot_flower" => Some(Self::PotFlower),
            "trigger_trapped_chest" => Some(Self::TriggerTrappedChest),
            "open_enderchest" => Some(Self::OpenEnderchest),
            "enchant_item" => Some(Self::EnchantItem),
            "play_record" => Some(Self::PlayRecord),
            "interact_with_furnace" => Some(Self::InteractWithFurnace),
            "interact_with_crafting_table" => Some(Self::InteractWithCraftingTable),
            "open_chest" => Some(Self::OpenChest),
            "sleep_in_bed" => Some(Self::SleepInBed),
            "open_shulker_box" => Some(Self::OpenShulkerBox),
            "open_barrel" => Some(Self::OpenBarrel),
            "interact_with_blast_furnace" => Some(Self::InteractWithBlastFurnace),
            "interact_with_smoker" => Some(Self::InteractWithSmoker),
            "interact_with_lectern" => Some(Self::InteractWithLectern),
            "interact_with_campfire" => Some(Self::InteractWithCampfire),
            "interact_with_cartography_table" => Some(Self::InteractWithCartographyTable),
            "interact_with_loom" => Some(Self::InteractWithLoom),
            "interact_with_stonecutter" => Some(Self::InteractWithStonecutter),
            "bell_ring" => Some(Self::BellRing),
            "raid_trigger" => Some(Self::RaidTrigger),
            "raid_win" => Some(Self::RaidWin),
            "interact_with_anvil" => Some(Self::InteractWithAnvil),
            "interact_with_grindstone" => Some(Self::InteractWithGrindstone),
            "target_hit" => Some(Self::TargetHit),
            "interact_with_smithing_table" => Some(Self::InteractWithSmithingTable),
            _ => None,
        }
    }
}
